### ISSUE TITLE
Got “client exception loading jobs details”

### ISSUE THREAD

**Issue by Anonym91** [Hygieia/hygieia-build-jenkins-collector#27]
Hi there, while run collector I've got error like below. And my version is Release3.1.0. Does collector relate to specified jenkins version?

2020-04-22 17:30:00,002 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Hudson
2020-04-22 17:30:00,030 [taskScheduler-1] INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:12, serverValue:234}] to localhost:27017
2020-04-22 17:30:00,036 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-04-22 17:30:00,036 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://192.168.1.193:8010/jenkins
2020-04-22 17:30:00,036 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-04-22 17:30:00,045 [taskScheduler-1] INFO  c.c.d.collector.DefaultHudsonClient - Fetching jobs 0/1 pageSize 1000...
2020-04-22 17:30:00,051 [taskScheduler-1] ERROR c.c.d.collector.DefaultHudsonClient - client exception loading jobs details
org.springframework.web.client.HttpClientErrorException: 400 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:572) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:493) ~[spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.makeRestCall(DefaultHudsonClient.java:650) ~[classes/:na]
	at com.capitalone.dashboard.collector.DefaultHudsonClient.getInstanceJobs(DefaultHudsonClient.java:126) ~[classes/:na]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:123) [classes/:na]
	at com.capitalone.dashboard.collector.HudsonCollectorTask.collect(HudsonCollectorTask.java:42) [classes/:na]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.2.jar:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
2020-04-22 17:30:00,051 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Error getting jobs for: http://192.168.1.193:8010/jenkins 0s

**Comment by Navya-V** [comment]
I have a similar issue @Sbrenthughes is there something wrong with the code?

**Comment by Navya-V** [comment]
@Anonym91 did u find the solution . i am facing a similar issue !!!can you post the solution?

**Comment by Anonym91** [comment]
> @Anonym91 did u find the solution . i am facing a similar issue !!!can you post the solution?

Unfortunatelynot yet.
